# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8nSafOP0SxqvVpcgVoX1bWabUQPa_6c

# Predição de Faixa Salarial

## Integrantes

- Aline Maria de Miranda Pereira
- Ellen Stefany da Silva
- Liz Rosa Nguyen
- Nicole Cristina dos Santos

## Sobre o Dataset

Nome: Adult Income Dataset

Link:
https://www.kaggle.com/datasets/wenruliu/adult-income-dataset

Contexto:
O dataset contém informações socioeconômicas de indivíduos e tem como objetivo prever se uma pessoa possui renda superior ou inferior a US$50.000 anuais.

Quantidade de registros:
48842

Quantidade de atributos:
15

Variável-alvo:
income (salário)

Tipo do problema:
Classificação
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)

from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style='whitegrid')
print('Bibliotecas carregadas com sucesso!')

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/adult-all.csv'

colunas = [
    'age', 'workclass', 'fnlwgt', 'education', 'educational-num',
    'marital-status', 'occupation', 'relationship', 'race', 'gender',
    'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income'
]

df = pd.read_csv(url, names=colunas, na_values=' ?')

df.rename(columns={
    'age': 'idade',
    'workclass': 'classe_de_trabalho',
    'fnlwgt': 'peso_amostral',
    'education': 'escolaridade',
    'educational-num': 'anos_de_escolaridade',
    'marital-status': 'estado_civil',
    'occupation': 'ocupacao',
    'relationship': 'relacao_familiar',
    'race': 'raca',
    'gender': 'sexo',
    'capital-gain': 'ganho_capital',
    'capital-loss': 'perda_capital',
    'hours-per-week': 'horas_semana',
    'native-country': 'pais_de_origem',
    'income': 'renda'
}, inplace=True)

df.dropna(inplace=True)
df = df.reset_index(drop=True)

print(f'DATASET')
print("\n")
print(f'Registros: {df.shape[0]}')
print(f'Atributos: {df.shape[1]}')
print("\n")
df.sample(10)

"""##peso_amostral (fnlwgt)
Esta variável representa o peso estatístico atribuído pelo Censo dos Estados Unidos a cada indivíduo da amostra. O valor indica quantas pessoas da população total são representadas por aquele registro.

## Exemplo:
Um indivíduo com peso_amostral = 100000 representa aproximadamente 100.000 pessoas com características semelhantes na população.

O peso amostral não descreve uma característica da pessoa, como idade, renda ou escolaridade. Ele é utilizado para que análises estatísticas produzam estimativas mais representativas da população real.
"""

print("ANÁLISE ESTATÍSTICA DO DATASET\n")

display(df.describe())

print("ANÁLISE ESTATÍSTICA - RESULTADOS INDIVIDUAIS")

colunas_numericas = [
    'idade',
    'peso_amostral',
    'anos_de_escolaridade',
    'ganho_capital',
    'perda_capital',
    'horas_semana'
]

for coluna in colunas_numericas:
    print(f"\n{coluna.upper()}\n")
    print(f"Média: {df[coluna].mean():.2f}")
    print(f"Mediana: {df[coluna].median():.2f}")
    print(f"Mínimo: {df[coluna].min()}")
    print(f"Máximo: {df[coluna].max()}")
    print(f"Desvio padrão: {df[coluna].std():.2f}")

print('DISTRIBUIÇÃO DA VARIÁVEL-ALVO (renda) \n')
print(df['renda'].value_counts())
print("\n")
print(df['renda'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')
print("\n")

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='renda', palette='Set2')
plt.title('Distribuição da Variável-Alvo (renda)')
plt.tight_layout()
plt.show()

"""Observação: O gráfico mostra que o dataset é desbalanceado.
A grande maioria das pessoas, cerca de 76%, ganha abaixo de
50K, enquanto apenas 24% ganham acima. Essa diferença pode
influenciar o modelo, que tende a acertar mais facilmente
quem ganha menos por ser a categoria mais comum nos dados.
"""

print("\nDISTRIBUIÇÃO DA RENDA\n")

quantidades = df['renda'].value_counts()
percentuais = df['renda'].value_counts(normalize=True) * 100

for categoria in quantidades.index:
    print(f"{categoria}:")
    print("\n")
    print(f"Quantidade: {quantidades[categoria]}")
    print(f"Percentual: {percentuais[categoria]:.2f}%")
    print("\n")

plt.figure(figsize=(7,5))
sns.countplot(data=df, x='sexo', hue='renda', palette='Set2')
plt.title('Distribuição de Renda por Gênero')
plt.xlabel('Gênero')
plt.ylabel('Quantidade')
plt.legend(title='Renda')
plt.tight_layout()
plt.show()

"""Observação: A maioria dos registros do dataset são de homens.
Além disso, a proporção de homens que ganham acima de 50K é
bem maior do que a de mulheres, mostrando uma diferença
significativa entre os gêneros na faixa salarial mais alta.
"""

plt.figure(figsize=(8,5))

sns.violinplot(
    data=df,
    x='renda',
    y='anos_de_escolaridade',
    palette='Set2',
)

plt.title('Impactos dos Anos de Escolaridade na Faixa de Renda')
plt.xlabel('Faixa Salarial')
plt.ylabel('Anos de Escolaridade')

plt.show()

"""Observação: Quanto mais anos de estudo, maior a chance de
ganhar acima de 50K. Pessoas com mais escolaridade aparecem
com mais frequência na faixa salarial mais alta.
"""

plt.figure(figsize=(8,5))
sns.histplot(data=df, x='idade', hue='renda', bins=30, kde=True, palette='Set2')
plt.title('Distribuição de Idade por Faixa Salarial')
plt.tight_layout()
plt.show()

"""Observação: O gráfico mostra que as pessoas que ganham acima
de 50K tendem a ter uma idade maior. A concentração de renda
mais alta aparece a partir dos 30 anos, enquanto os mais jovens,
por volta dos 20 anos, estão majoritariamente na faixa abaixo de 50K.

#Preparação dos dados

Antes da aplicação de técnicas de análise estatística e aprendizado de máquina, é preciso realizar o pré-processamento dos dados: preparar o conjunto de dados para que todas as variáveis possam ser corretamente interpretadas pelos modelos computacionais.

Para tanto, foi realizada a cópia dos dados, para que o conjunto original não se perdesse / fosse alterado.  

Em seguida, houve o tratamento da variável-alvo "renda", pelo método strip(), que remove os espaços em branco na coluna.

Posteriormente, os valores de renda foram convertidos para representaçoes númericas binárias.

0 -> renda anual menor ou igual a 50k.

1 -> renda anual superior a 50k.

Nas demais variáveis, que tinham seus resultados expressos em textos, foi empregada a técnica de Label Enconding: consiste em atribuir um identificador numérico para cada categoria existente em uma variável.

Por exemplo, uma coluna contendo os valores "Masculino" e "Feminino" pode ser convertida para os valores 1 e 0, respectivamente. Da mesma forma, diferentes níveis de escolaridade, ocupações ou estados civis passam a ser representados por códigos numéricos.
"""

df_modelo = df.copy()

df_modelo['renda'] = df_modelo['renda'].str.strip()
df_modelo['renda'] = df_modelo['renda'].map({'<=50K': 0, '>50K': 1})

le = LabelEncoder()
colunas_cat = ['classe_de_trabalho','escolaridade','estado_civil',
               'ocupacao','relacao_familiar','raca','sexo','pais_de_origem']

for col in colunas_cat:
    df_modelo[col] = le.fit_transform(df_modelo[col])

print('PRÉ-PROCESSAMENTO DOS DADOS\n')
df_modelo.sample(10)

print("TREINAMENTO E TESTAGEM\n")

X = df_modelo.drop(columns=['renda', 'peso_amostral'])
y = df_modelo['renda']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f'Treino: {X_train.shape[0]} registros')
print(f'Teste:  {X_test.shape[0]} registros')

modelo_base = LogisticRegression(max_iter=1000, random_state=42)
modelo_base.fit(X_train, y_train)
y_pred_base = modelo_base.predict(X_test)

print('MODELO BASE\n')
print(f'Acurácia: {accuracy_score(y_test, y_pred_base):.4f}')
print(f'Precisão: {precision_score(y_test, y_pred_base):.4f}')
print(f'Recall:   {recall_score(y_test, y_pred_base):.4f}')
print(f'F1-Score: {f1_score(y_test, y_pred_base):.4f}')

cm = confusion_matrix(y_test, y_pred_base)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['<=50K','>50K'],
            yticklabels=['<=50K','>50K'])
plt.title('Matriz de Confusão — Modelo Base')
plt.xlabel('Previsto')
plt.ylabel('Real')
plt.tight_layout()
plt.show()

print(classification_report(y_test, y_pred_base, target_names=['<=50K','>50K']))

"""## Modelo Utilizado

### Nome do modelo
Regressão Logística

### Objetivo do modelo
Classificar se uma pessoa ganha acima ou abaixo de 50K,
com base nas suas informações pessoais como idade,
escolaridade e ocupação.

### Como o modelo funciona
Esse modelo lê as informações de uma pessoa e calcula
as chances dela ganhar acima ou abaixo de 50K.
Internamente ele transforma esses dados em um número
entre 0 e 1. Se esse número passar de 0,5 o modelo
classifica como acima de 50K, se não, classifica
como abaixo.

### Por que escolhemos esse modelo?
Escolhemos esse modelo porque o nosso problema tinha
só duas respostas possíveis: ganha acima ou abaixo
de 50K. Além disso ele é fácil de interpretar e de
explicar, o que ajudou bastante no desenvolvimento
do projeto.
"""

coeficientes = pd.DataFrame({
    'Atributo': X.columns,
    'Coeficiente': modelo_base.coef_[0]
}).sort_values('Coeficiente', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(data=coeficientes, x='Coeficiente', y='Atributo', palette='coolwarm')
plt.title('Importância dos Atributos — Regressão Logística')
plt.xlabel('Coeficiente')
plt.ylabel('Atributo')
plt.axvline(0, color='black', linewidth=0.8)
plt.tight_layout()
plt.show()

print('\nAtributos com coeficiente positivo aumentam a chance de renda > 50K.')
print('Atributos com coeficiente negativo reduzem essa chance.')

X_train_e1, X_test_e1, y_train_e1, y_test_e1 = train_test_split(
    X, y, test_size=0.3, random_state=42
)
modelo_e1 = LogisticRegression(max_iter=1000, random_state=42)
modelo_e1.fit(X_train_e1, y_train_e1)
y_pred_e1 = modelo_e1.predict(X_test_e1)

print('EXPERIMENTO 1: Divisão 70/30\n')
print(f'Acurácia: {accuracy_score(y_test_e1, y_pred_e1):.4f}')
print(f'Precisão: {precision_score(y_test_e1, y_pred_e1):.4f}')
print(f'Recall:   {recall_score(y_test_e1, y_pred_e1):.4f}')
print(f'F1-Score: {f1_score(y_test_e1, y_pred_e1):.4f}')

"""  ## Experimento 1 – Regressão Logística com Divisão 70/30

Neste experimento foi utilizado o algoritmo de **Regressão Logística** para realizar uma classificação dos dados. Para isso, o conjunto de dados foi dividido em duas partes: **70% para treinamento** e **30% para teste**.

A etapa de treinamento foi realizada utilizando 70% dos dados disponíveis, permitindo que o modelo aprendesse os padrões existentes no conjunto. Em seguida, os 30% restantes foram utilizados para testar o desempenho do modelo em dados que ele não havia visto anteriormente.

Após o treinamento, foram calculadas algumas métricas para avaliar a qualidade das previsões realizadas pelo modelo.

### Resultados Obtidos

- **Acurácia:** 82,19%
- **Precisão:** 71,34%
- **Recall:** 44,05%
- **F1-Score:** 54,47%

### Análise dos Resultados

A **acurácia** de 82,19% indica que o modelo acertou a maioria das classificações realizadas no conjunto de teste. Esse resultado mostra que, de forma geral, o modelo apresentou um bom desempenho.

A **precisão** de 71,34% demonstra que, quando o modelo classificou um caso como positivo, ele acertou essa previsão na maior parte das vezes.

Já o **recall** apresentou valor de 44,05%, indicando que o modelo encontrou menos da metade dos casos positivos existentes no conjunto de teste. Isso significa que alguns exemplos positivos não foram identificados corretamente.

O **F1-Score**, que combina precisão e recall em uma única métrica, foi de 54,47%. Esse valor mostra que existe um desequilíbrio entre essas duas métricas, principalmente devido ao recall mais baixo.

### Conclusão

Os resultados mostram que a Regressão Logística conseguiu atingir uma boa taxa de acertos gerais, representada pela acurácia de 82,19%. No entanto, o modelo ainda apresenta dificuldades para identificar todos os casos positivos, como pode ser observado pelo valor do recall.

De maneira geral, o experimento demonstrou que o modelo possui um desempenho satisfatório, mas ainda há espaço para melhorias visando aumentar a identificação correta dos casos positivos e melhorar o equilíbrio entre as métricas de avaliação.
"""

modelo_e2 = LogisticRegression(max_iter=5000, random_state=42)
modelo_e2.fit(X_train, y_train)
y_pred_e2 = modelo_e2.predict(X_test)

print('EXPERIMENTO 2: max_iter=5000\n')
print(f'Acurácia: {accuracy_score(y_test, y_pred_e2):.4f}')
print(f'Precisão: {precision_score(y_test, y_pred_e2):.4f}')
print(f'Recall:   {recall_score(y_test, y_pred_e2):.4f}')
print(f'F1-Score: {f1_score(y_test, y_pred_e2):.4f}')

"""## Experimento 2 – Regressão Logística com Aumento do Número de Iterações

Neste experimento foi utilizado o mesmo algoritmo de **Regressão Logística**, porém aumentando o parâmetro `max_iter` de 1000 para 5000. Esse parâmetro define o número máximo de iterações que o algoritmo pode executar durante o treinamento para encontrar a melhor solução.

O objetivo deste teste foi verificar se permitir mais iterações poderia melhorar o desempenho do modelo. Para manter uma comparação justa com o Experimento 1, foram utilizados os mesmos conjuntos de treinamento e teste.

Após o treinamento, o modelo foi avaliado utilizando as métricas de acurácia, precisão, recall e F1-Score.

### Resultados Obtidos

- **Acurácia:** 82,52%
- **Precisão:** 72,33%
- **Recall:** 44,50%
- **F1-Score:** 55,10%

### Análise dos Resultados

A **acurácia** aumentou levemente para 82,52%, indicando uma pequena melhora na quantidade total de classificações corretas realizadas pelo modelo.

A **precisão** passou para 72,33%, mostrando que o modelo ficou um pouco mais confiável ao classificar casos positivos.

O **recall** também apresentou uma pequena melhora, atingindo 44,50%. Apesar do aumento, o modelo ainda deixa de identificar uma parcela significativa dos casos positivos existentes.

O **F1-Score** subiu para 55,10%, refletindo o ganho observado tanto na precisão quanto no recall.

### Comparação com o Experimento 1

Ao comparar os resultados dos dois experimentos, observa-se que o aumento do parâmetro `max_iter` trouxe uma melhora discreta em todas as métricas avaliadas.

| Métrica | Experimento 1 | Experimento 2 |
|----------|----------|----------|
| Acurácia | 82,19% | 82,52% |
| Precisão | 71,34% | 72,33% |
| Recall | 44,05% | 44,50% |
| F1-Score | 54,47% | 55,10% |

### Conclusão

Os resultados mostram que aumentar o número máximo de iterações permitiu que o algoritmo encontrasse uma solução ligeiramente melhor, resultando em pequenos ganhos em todas as métricas avaliadas. No entanto, as diferenças foram relativamente pequenas, indicando que o modelo já estava próximo da convergência no Experimento 1.

Dessa forma, embora o aumento de `max_iter` tenha gerado uma melhora no desempenho, o impacto foi limitado. Para obter ganhos mais significativos, pode ser necessário explorar outras estratégias, como ajustes de hiperparâmetros, seleção de atributos ou utilização de algoritmos diferentes.
"""

X_red = df_modelo[['idade','anos_de_escolaridade', 'ganho_capital',
                    'perda_capital','horas_semana','sexo',
                    'estado_civil','ocupacao']]
y_red = df_modelo['renda']

X_train_e3, X_test_e3, y_train_e3, y_test_e3 = train_test_split(
    X_red, y_red, test_size=0.2, random_state=42
)
modelo_e3 = LogisticRegression(max_iter=1000, random_state=42)
modelo_e3.fit(X_train_e3, y_train_e3)
y_pred_e3 = modelo_e3.predict(X_test_e3)

print('EXPERIMENTO 3: 8 atributos principais\n')
print(f'Acurácia: {accuracy_score(y_test_e3, y_pred_e3):.4f}')
print(f'Precisão: {precision_score(y_test_e3, y_pred_e3):.4f}')
print(f'Recall:   {recall_score(y_test_e3, y_pred_e3):.4f}')
print(f'F1-Score: {f1_score(y_test_e3, y_pred_e3):.4f}')

"""**Hipótese proposta:** Se utilizarmos apenas 8 variáveis, o modelo pode manter um desempenho semelhante ao modelo original, pois algumas variáveis não auxiliam na predição da faixa salarial.

**Parâmetro alterado:** Os parâmetros alternados foram as variáveis utilizadas na execucão, que passaram de 13 para 8.

**Configuração inicial:** O modelo original utilizava 13 variáveis, com divisão de 80% para treino e 20% para teste, e max_iter de 1000.

**Nova configuração testada:** No experimento 3 foram utilizadas 8 variáveis, com divisão de 80% para treino e 20% para teste, e max_iter de 1000.

**Métricas obtidas:**
| Métrica   | Modelo Original | Experimento 3 |
|-----------|-----------------|---------------|
| Acurácia  | 0.8214          | 0.8214        |
| Precisão  | 0.7166          | 0.7121        |
| Recall    | 0.4285          | 0.4348        |
| F1-Score  | 0.5363          | 0.5399        |

**Comparação com a execução inicial:** No modelo original a acurácia permaneceu igual em 0.8214. A precisão diminuiu de 0.7166 para 0.7121. O recall aumentou de 0.4285 para 0.4348. O F1-Score aumentou de 0.5363 para 0.5399.

**Conclusão sobre o resultado observado:** A hipótese foi validada, pois utilizando apenas 8 variáveis, o modelo manteve um desempenho semelhante ao modelo original. Portanto, as 5 variáveis eliminadas eram dispensáveis para a predição salarial.

"""

print("EXPERIMENTOS: RESULTADOS\n")

resultados = pd.DataFrame({
    'Experimento': [
        'Baseline (80/20)',
        'Exp 1 - Divisão 70/30',
        'Exp 2 - max_iter=5000',
        'Exp 3 - 8 atributos'
    ],
    'Acurácia': [
        accuracy_score(y_test, y_pred_base),
        accuracy_score(y_test_e1, y_pred_e1),
        accuracy_score(y_test, y_pred_e2),
        accuracy_score(y_test_e3, y_pred_e3)
    ],
    'F1-Score': [
        f1_score(y_test, y_pred_base),
        f1_score(y_test_e1, y_pred_e1),
        f1_score(y_test, y_pred_e2),
        f1_score(y_test_e3, y_pred_e3)
    ]
}).round(4)

print(resultados.to_string(index=False))

"""**Conclusão**


O modelo de Regressão Logística foi eficaz para prever  a faixa salarial, acertando cerca de 82% das previsões. O experimento 2 obteve melhor resultado com max_iter=5000, pois apresentou o maior F1-Score de 0.5510. O projeto mostrou que variáveis como escolaridade, ocupação e estado civil são fundamentais para a previsão salarial. Portanto, apesar de bom desempenho, o modelo apresentou dificuldades em identificar corretamente as pessoas que ganham acima de 50K.
"""